import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import ColumnLayout from '@cloudscape-design/components/column-layout';
import Box from '@cloudscape-design/components/box';
import Header from '@cloudscape-design/components/header';
import Alert from '@cloudscape-design/components/alert';
import Spinner from '@cloudscape-design/components/spinner';
import SpaceBetween from '@cloudscape-design/components/space-between';
import Container from '@cloudscape-design/components/container';
import Badge from '@cloudscape-design/components/badge';
import Button from '@cloudscape-design/components/button';
import CloudscapeShell from '../components/CloudscapeShell';
import AttackFlowViewer from '../components/AttackFlowViewer';
import MitigationsTable from '../components/MitigationsTable';
import ExportButton from '../components/ExportButton';
import { getApplication, getApplicationVersions } from '../api-client';

function PriorityBadge({ priority }) {
  const colorMap = { High: 'red', Medium: 'grey', Low: 'green' };
  return <Badge color={colorMap[priority] || 'grey'}>{priority || '\u2014'}</Badge>;
}

function SummaryBar({ data }) {
  const ext = data?.extraction_summary || {};
  const map = data?.mapping_summary || {};
  return (
    <Container>
      <ColumnLayout columns={4} variant="text-grid">
        <div><Box variant="awsui-key-label">Total Threats</Box>
          <div style={{ fontSize: '24px', fontWeight: 700 }}>{ext.total_threats ?? 0}</div></div>
        <div><Box variant="awsui-key-label">High Severity</Box>
          <div style={{ fontSize: '24px', fontWeight: 700, color: '#d13212' }}>{ext.high_severity_count ?? 0}</div></div>
        <div><Box variant="awsui-key-label">Attack Trees</Box>
          <div style={{ fontSize: '24px', fontWeight: 700 }}>{(data?.attack_trees || []).length}</div></div>
        <div><Box variant="awsui-key-label">TTP Mappings</Box>
          <div style={{ fontSize: '24px', fontWeight: 700 }}>{map.total_mappings ?? 0}</div></div>
      </ColumnLayout>
    </Container>
  );
}

function ThreatDetailsBar({ tree }) {
  if (!tree) return null;
  return (
    <Container>
      <ColumnLayout columns={2} variant="text-grid">
        <div><Box variant="awsui-key-label">Threat Statement</Box>
          <div>{tree.threat_statement || '\u2014'}</div></div>
        <div><SpaceBetween size="m">
          <div><Box variant="awsui-key-label">Priority</Box><PriorityBadge priority={tree.priority} /></div>
          <div><Box variant="awsui-key-label">Action</Box><div>{tree.threat_action || '\u2014'}</div></div>
          <div><Box variant="awsui-key-label">Source</Box><div>{tree.threatSource === 'generated' ? 'Generated by ThreatForest' : tree.threatSource || '\u2014'}</div></div>
        </SpaceBetween></div>
      </ColumnLayout>
    </Container>
  );
}


export default function VersionDetailPage() {
  const { appId, versionId, threatIndex } = useParams();
  const navigate = useNavigate();
  const selectedIdx = parseInt(threatIndex || '0', 10);
  const [data, setData] = useState(null);
  const [appName, setAppName] = useState(appId);
  // True once a persistent app record is found — blocks the legacy
  // project_info.application_name fallback from clobbering the real name.
  const [persistentAppLoaded, setPersistentAppLoaded] = useState(false);
  const [versionLabel, setVersionLabel] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    let cancelled = false;
    async function fetchVersion() {
      try {
        setLoading(true); setError(null);
        const response = await fetch(`/api/applications/${encodeURIComponent(appId)}/versions/${encodeURIComponent(versionId)}/data`);
        if (!response.ok) throw new Error(`Failed to load (HTTP ${response.status})`);
        const json = await response.json();
        if (cancelled) return;
        setData(json);
        if (!persistentAppLoaded) {
          if (json.project_info?.application_name) setAppName(json.project_info.application_name);
          else if (json.application_name) setAppName(json.application_name);
        }
      } catch (err) {
        if (!cancelled) setError(err.message || 'Failed to load');
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    fetchVersion();
    return () => { cancelled = true; };
  }, [appId, versionId, persistentAppLoaded]);

  // Authoritative app name from the persistent record (works for both
  // opaque app_id and folder-slug URLs thanks to the /by-id fallback).
  useEffect(() => {
    let cancelled = false;
    getApplication(appId)
      .then((app) => {
        if (cancelled || !app?.name) return;
        setAppName(app.name);
        setPersistentAppLoaded(true);
      })
      .catch(() => { /* keep legacy fallback */ });
    return () => { cancelled = true; };
  }, [appId]);

  // Friendly version label for the breadcrumb.
  useEffect(() => {
    let cancelled = false;
    if (versionId === 'latest') {
      setVersionLabel('Latest');
      return () => { cancelled = true; };
    }
    getApplicationVersions(appId)
      .then(({ versions = [] }) => {
        if (cancelled) return;
        const match = versions.find((v) => v.id === versionId);
        setVersionLabel(match?.display_name || versionId);
      })
      .catch(() => { if (!cancelled) setVersionLabel(versionId); });
    return () => { cancelled = true; };
  }, [appId, versionId]);

  const attackTrees = data?.attack_trees || [];
  const selectedTree = attackTrees[selectedIdx] || null;
  const threatLabel = selectedTree
    ? `${selectedTree.threat_id || `Threat ${selectedIdx + 1}`} \u2014 ${selectedTree.threat_category || 'Unknown'}`
    : `Threat ${selectedIdx + 1}`;

  return (
    <CloudscapeShell
      activePage="/applications"
      breadcrumbs={[
        { text: 'Home', href: '/' },
        { text: 'Applications', href: '/applications' },
        { text: appName, href: `/applications/${appId}` },
        {
          text: versionLabel || 'Latest threat model',
          href: `/applications/${appId}/versions/${versionId}`,
        },
        { text: threatLabel, href: `/applications/${appId}/versions/${versionId}/threats/${threatIndex}` },
      ]}
    >
      {error && <Alert type="error" header="Error loading dashboard">{error}</Alert>}
      {loading ? (
        <Box textAlign="center" padding="l" data-testid="loading-spinner"><Spinner size="large" /></Box>
      ) : data ? (
        <SpaceBetween size="m">
          <Header variant="h1" actions={
            <SpaceBetween direction="horizontal" size="xs">
              <Button
                iconName="angle-left"
                variant="icon"
                disabled={selectedIdx <= 0}
                onClick={() => navigate(`/applications/${appId}/versions/${versionId}/threats/${selectedIdx - 1}`)}
                ariaLabel="Previous threat"
              />
              <Box variant="p" display="inline" padding={{ top: 'xxs' }}>
                {selectedIdx + 1} / {attackTrees.length}
              </Box>
              <Button
                iconName="angle-right"
                variant="icon"
                disabled={selectedIdx >= attackTrees.length - 1}
                onClick={() => navigate(`/applications/${appId}/versions/${versionId}/threats/${selectedIdx + 1}`)}
                ariaLabel="Next threat"
              />
              <ExportButton
                summaryData={data}
                appId={appId}
                versionId={versionId}
              />
            </SpaceBetween>
          }>{threatLabel}</Header>
          {selectedTree && <ThreatDetailsBar tree={selectedTree} />}
          {selectedTree && (
            <div>
              <Header variant="h3">Attack Tree</Header>
              <Box variant="p" color="text-status-inactive" fontSize="body-s" margin={{ bottom: 'xs' }}>
                Click any node to view and edit its properties in the right panel.
              </Box>
              <div style={{
                border: '1px solid #d5dbdb',
                borderRadius: 8,
                overflow: 'hidden',
              }}>
                <AttackFlowViewer attackTree={selectedTree} />
              </div>
            </div>
          )}
          {selectedTree && <MitigationsTable attackTree={selectedTree} />}
          {!selectedTree && (
            <Box color="text-status-inactive" textAlign="center" padding="l">
              Attack tree not found for this threat.
            </Box>
          )}
        </SpaceBetween>
      ) : null}
    </CloudscapeShell>
  );
}
