"""
Information saver for validated application information.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

from .models import ApplicationInfo
from .utils import get_logger, ensure_output_directory


class InfoSaver:
    """Saves validated application information to markdown file."""
    
    def __init__(self, output_directory: str):
        self.output_directory = Path(output_directory)
        self.logger = get_logger(__name__)
    
    def save_application_info(self, app_info: ApplicationInfo) -> Path:
        """
        Save application information to markdown file.
        
        Args:
            app_info: Validated application information
            
        Returns:
            Path to saved file
        """
        # Ensure output directory exists
        ensure_output_directory(str(self.output_directory))
        
        # Create output file path
        output_file = self.output_directory / "extracted_info.md"
        
        # Generate markdown content
        markdown_content = self._generate_markdown(app_info)
        
        # Write to file
        try:
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(markdown_content)
            
            self.logger.info(f"Application information saved to: {output_file}")
            return output_file
            
        except Exception as e:
            self.logger.error(f"Failed to save application information: {e}")
            raise
    
    def _generate_markdown(self, app_info: ApplicationInfo) -> str:
        """Generate markdown content from application info."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        content = f"""# Application Information

*Generated by ThreatForest on {timestamp}*

## Overview

**Application Name:** {app_info.name}

**Description:** {app_info.description or 'No description provided'}

**Sector:** {app_info.sector or 'Not specified'}

## Technical Details

### Technologies Used
{self._format_list(app_info.technologies)}

### Programming Languages
{self._format_list(app_info.programming_languages)}

## Security Information

### Security Objectives
{self._format_list(app_info.security_objectives)}

The security objectives indicate the priority order for Confidentiality, Integrity, and Availability (CIA triad) for this application.

## Additional Context
{self._format_additional_context(app_info.additional_context)}

---

*This information was extracted from application context files and validated by the user. It will be used to generate contextually relevant attack trees.*
"""
        return content
    
    def _format_list(self, items: list) -> str:
        """Format a list as markdown bullet points."""
        if not items:
            return "- None specified\n"
        
        return "\n".join(f"- {item}" for item in items) + "\n"
    
    def _format_additional_context(self, context: Dict[str, Any]) -> str:
        """Format additional context as markdown."""
        if not context:
            return "No additional context provided.\n"
        
        formatted_parts = []
        
        for key, value in context.items():
            if key == 'source_files':
                # Skip internal metadata
                continue
            
            formatted_key = key.replace('_', ' ').title()
            
            if isinstance(value, (list, dict)):
                formatted_value = json.dumps(value, indent=2)
                formatted_parts.append(f"**{formatted_key}:**\n```json\n{formatted_value}\n```\n")
            else:
                formatted_parts.append(f"**{formatted_key}:** {value}\n")
        
        return "\n".join(formatted_parts) if formatted_parts else "No additional context provided.\n"
    
    def save_processing_metadata(self, metadata: Dict[str, Any]) -> Path:
        """
        Save processing metadata for debugging and audit purposes.
        
        Args:
            metadata: Processing metadata dictionary
            
        Returns:
            Path to saved metadata file
        """
        metadata_file = self.output_directory / "processing_metadata.json"
        
        try:
            with open(metadata_file, 'w', encoding='utf-8') as f:
                json.dump(metadata, f, indent=2, default=str)
            
            self.logger.debug(f"Processing metadata saved to: {metadata_file}")
            return metadata_file
            
        except Exception as e:
            self.logger.warning(f"Failed to save processing metadata: {e}")
            return metadata_file