"""
Summary generation and reporting functionality for ThreatForest.
"""

from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional

from .models import ApplicationInfo, ThreatStatement, AttackTree
from .utils import get_logger


class SummaryGenerator:
    """Generates comprehensive summary reports for ThreatForest analysis."""
    
    def __init__(self, output_directory: str):
        self.output_directory = Path(output_directory)
        self.logger = get_logger(__name__)
    
    def generate_summary(
        self,
        app_info: ApplicationInfo,
        threats: List[ThreatStatement],
        attack_trees: List[AttackTree],
        processing_stats: Optional[Dict[str, Any]] = None
    ) -> Path:
        """
        Generate comprehensive summary report.
        
        Args:
            app_info: Application information
            threats: List of processed threats
            attack_trees: List of generated attack trees
            processing_stats: Optional processing statistics
            
        Returns:
            Path to generated summary file
        """
        self.logger.info("Generating comprehensive summary report")
        
        summary_file = self.output_directory / "summary.md"
        
        # Generate summary content
        summary_content = self._generate_summary_content(
            app_info, threats, attack_trees, processing_stats
        )
        
        # Write to file
        with open(summary_file, 'w', encoding='utf-8') as f:
            f.write(summary_content)
        
        self.logger.info(f"Summary report saved to: {summary_file}")
        return summary_file
    
    def _generate_summary_content(
        self,
        app_info: ApplicationInfo,
        threats: List[ThreatStatement],
        attack_trees: List[AttackTree],
        processing_stats: Optional[Dict[str, Any]]
    ) -> str:
        """Generate the complete summary content."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        content = f"""# ThreatForest Analysis Summary

**Generated:** {timestamp}
**Analysis Target:** {app_info.name}

## Executive Summary

This report presents the results of an automated threat analysis conducted using ThreatForest. The analysis identified and processed {len(threats)} high-severity threats, generating {len(attack_trees)} detailed attack trees enhanced with MITRE ATT&CK technique mappings.

## Application Overview

**Name:** {app_info.name}
**Description:** {app_info.description or 'No description provided'}
**Sector:** {app_info.sector or 'Not specified'}

### Technology Stack
{self._format_technology_stack(app_info)}

### Security Objectives
{self._format_security_objectives(app_info)}

## Threat Analysis Results

### Summary Statistics
- **Total Threats Processed:** {len(threats)}
- **Attack Trees Generated:** {len(attack_trees)}
- **Success Rate:** {(len(attack_trees) / len(threats) * 100) if threats else 0:.1f}%

### Threat Breakdown by Severity
{self._generate_threat_breakdown(threats)}

## Generated Attack Trees

{self._generate_attack_trees_section(attack_trees, threats)}

## MITRE ATT&CK Analysis

{self._generate_mitre_analysis(attack_trees)}

## Processing Statistics

{self._generate_processing_stats(processing_stats)}

## Recommendations

{self._generate_recommendations(app_info, threats, attack_trees)}

## Files Generated

{self._generate_files_list(attack_trees)}

---

*This report was automatically generated by ThreatForest v0.1.0*
*For questions or issues, please refer to the ThreatForest documentation*
"""
        
        return content
    
    def _format_technology_stack(self, app_info: ApplicationInfo) -> str:
        """Format technology stack information."""
        if not app_info.technologies and not app_info.programming_languages:
            return "- No technology information available\n"
        
        content = ""
        
        if app_info.programming_languages:
            content += f"**Programming Languages:** {', '.join(app_info.programming_languages)}\n"
        
        if app_info.technologies:
            content += f"**Technologies & Frameworks:** {', '.join(app_info.technologies)}\n"
        
        return content
    
    def _format_security_objectives(self, app_info: ApplicationInfo) -> str:
        """Format security objectives information."""
        if not app_info.security_objectives:
            return "- Security objectives not specified\n"
        
        content = "**Priority Order (CIA Triad):**\n"
        for i, objective in enumerate(app_info.security_objectives, 1):
            content += f"{i}. {objective}\n"
        
        return content
    
    def _generate_threat_breakdown(self, threats: List[ThreatStatement]) -> str:
        """Generate threat breakdown by severity."""
        if not threats:
            return "No threats were processed.\n"
        
        # Count by severity
        severity_counts = {}
        for threat in threats:
            severity = threat.severity or 'unknown'
            severity_counts[severity] = severity_counts.get(severity, 0) + 1
        
        content = ""
        for severity in ['high', 'medium', 'low', 'unknown']:
            count = severity_counts.get(severity, 0)
            if count > 0:
                content += f"- **{severity.title()}:** {count} threats\n"
        
        return content
    
    def _generate_attack_trees_section(self, attack_trees: List[AttackTree], threats: List[ThreatStatement]) -> str:
        """Generate attack trees section with links."""
        if not attack_trees:
            return "No attack trees were generated.\n"
        
        content = "The following attack trees were generated for high-severity threats:\n\n"
        
        # Create threat lookup
        threat_lookup = {t.id: t for t in threats}
        
        for tree in attack_trees:
            threat = threat_lookup.get(tree.threat_id)
            severity = threat.severity if threat else 'unknown'
            
            # Create relative path for link
            tree_path = Path(tree.file_path)
            relative_path = tree_path.relative_to(self.output_directory)
            
            content += f"### [{tree.title}]({relative_path})\n"
            content += f"- **Threat ID:** {tree.threat_id}\n"
            content += f"- **Severity:** {severity.title()}\n"
            content += f"- **Attack Steps:** {len(tree.attack_steps)}\n"
            
            # Count MITRE techniques
            mitre_count = sum(1 for step in tree.attack_steps if step.mitre_techniques)
            if mitre_count > 0:
                content += f"- **MITRE ATT&CK Mappings:** {mitre_count} steps mapped\n"
            
            content += "\n"
        
        return content
    
    def _generate_mitre_analysis(self, attack_trees: List[AttackTree]) -> str:
        """Generate MITRE ATT&CK analysis section."""
        if not attack_trees:
            return "No MITRE ATT&CK analysis available.\n"
        
        # Collect all techniques and tactics
        all_techniques = set()
        all_tactics = set()
        technique_frequency = {}
        
        for tree in attack_trees:
            for step in tree.attack_steps:
                if step.mitre_techniques:
                    for tech_id in step.mitre_techniques:
                        all_techniques.add(tech_id)
                        technique_frequency[tech_id] = technique_frequency.get(tech_id, 0) + 1
        
        if not all_techniques:
            return "No MITRE ATT&CK techniques were mapped.\n"
        
        content = f"**Total Unique Techniques Identified:** {len(all_techniques)}\n\n"
        
        # Most common techniques
        if technique_frequency:
            sorted_techniques = sorted(technique_frequency.items(), key=lambda x: x[1], reverse=True)
            content += "### Most Frequently Mapped Techniques\n\n"
            
            for tech_id, count in sorted_techniques[:10]:  # Top 10
                content += f"- [{tech_id}](https://attack.mitre.org/techniques/{tech_id.replace('.', '/')}/): {count} occurrences\n"
            
            content += "\n"
        
        # Coverage analysis
        total_steps = sum(len(tree.attack_steps) for tree in attack_trees)
        mapped_steps = sum(1 for tree in attack_trees for step in tree.attack_steps if step.mitre_techniques)
        
        if total_steps > 0:
            coverage = (mapped_steps / total_steps) * 100
            content += f"### Coverage Analysis\n\n"
            content += f"- **Total Attack Steps:** {total_steps}\n"
            content += f"- **Steps with MITRE Mappings:** {mapped_steps}\n"
            content += f"- **Coverage Rate:** {coverage:.1f}%\n\n"
        
        return content
    
    def _generate_processing_stats(self, processing_stats: Optional[Dict[str, Any]]) -> str:
        """Generate processing statistics section."""
        if not processing_stats:
            return "Processing statistics not available.\n"
        
        content = ""
        
        # File processing stats
        if 'files_processed' in processing_stats:
            content += f"**Files Processed:** {processing_stats['files_processed']}\n"
        
        # LLM usage stats
        if 'llm_calls' in processing_stats:
            content += f"**LLM API Calls:** {processing_stats['llm_calls']}\n"
        
        if 'total_tokens' in processing_stats:
            content += f"**Total Tokens Used:** {processing_stats['total_tokens']:,}\n"
        
        # Processing time
        if 'processing_time' in processing_stats:
            content += f"**Total Processing Time:** {processing_stats['processing_time']:.1f} seconds\n"
        
        # Error stats
        if 'errors' in processing_stats and processing_stats['errors']:
            content += f"**Errors Encountered:** {len(processing_stats['errors'])}\n"
        
        return content
    
    def _generate_recommendations(
        self, 
        app_info: ApplicationInfo, 
        threats: List[ThreatStatement], 
        attack_trees: List[AttackTree]
    ) -> str:
        """Generate recommendations based on analysis results."""
        recommendations = []
        
        # Technology-specific recommendations
        if 'web' in ' '.join(app_info.technologies).lower():
            recommendations.append(
                "**Web Application Security:** Consider implementing Web Application Firewall (WAF) "
                "and regular security testing for web-facing components."
            )
        
        if 'cloud' in ' '.join(app_info.technologies + [app_info.additional_context.get('deployment_model', '')]).lower():
            recommendations.append(
                "**Cloud Security:** Review cloud security configurations, implement least-privilege "
                "access controls, and enable comprehensive logging."
            )
        
        # Threat-based recommendations
        if len(threats) > 5:
            recommendations.append(
                "**High Threat Volume:** With multiple high-severity threats identified, prioritize "
                "implementing defense-in-depth strategies and regular security assessments."
            )
        
        # MITRE ATT&CK based recommendations
        if attack_trees:
            # Count mitigation steps
            mitigation_count = sum(
                1 for tree in attack_trees 
                for step in tree.attack_steps 
                if step.node_type == 'mitigation'
            )
            
            if mitigation_count < len(attack_trees) * 2:  # Less than 2 mitigations per tree
                recommendations.append(
                    "**Insufficient Mitigations:** Consider implementing additional security controls "
                    "and defensive measures based on the identified attack paths."
                )
        
        # Security objectives recommendations
        if 'Confidentiality' in app_info.security_objectives[:1]:  # Top priority
            recommendations.append(
                "**Confidentiality Focus:** Implement strong encryption, access controls, and data "
                "classification to protect sensitive information."
            )
        
        if not recommendations:
            recommendations.append(
                "**General Recommendation:** Regularly review and update security measures based on "
                "the identified threats and attack patterns."
            )
        
        return "\n\n".join(recommendations) + "\n"
    
    def _generate_files_list(self, attack_trees: List[AttackTree]) -> str:
        """Generate list of files created during analysis."""
        content = "The following files were generated during this analysis:\n\n"
        
        # Main files
        content += "### Main Reports\n"
        content += "- `summary.md` - This comprehensive summary report\n"
        content += "- `extracted_info.md` - Validated application information\n\n"
        
        # Attack tree files
        if attack_trees:
            content += "### Attack Trees\n"
            for tree in attack_trees:
                tree_path = Path(tree.file_path)
                relative_path = tree_path.relative_to(self.output_directory)
                content += f"- `{relative_path}` - {tree.title}\n"
            content += "\n"
        
        # Log files
        content += "### Log Files\n"
        content += "- `logs/threat_forest.log` - Detailed processing logs\n\n"
        
        return content
    
    def generate_json_summary(
        self,
        app_info: ApplicationInfo,
        threats: List[ThreatStatement],
        attack_trees: List[AttackTree],
        processing_stats: Optional[Dict[str, Any]] = None
    ) -> Path:
        """
        Generate machine-readable JSON summary.
        
        Args:
            app_info: Application information
            threats: List of processed threats
            attack_trees: List of generated attack trees
            processing_stats: Optional processing statistics
            
        Returns:
            Path to generated JSON summary file
        """
        import json
        
        summary_file = self.output_directory / "summary.json"
        
        # Collect MITRE techniques
        all_techniques = {}
        for tree in attack_trees:
            for step in tree.attack_steps:
                if step.mitre_techniques:
                    for tech_id in step.mitre_techniques:
                        all_techniques[tech_id] = all_techniques.get(tech_id, 0) + 1
        
        summary_data = {
            "metadata": {
                "generated_at": datetime.now().isoformat(),
                "threat_forest_version": "0.1.0",
                "analysis_target": app_info.name
            },
            "application": {
                "name": app_info.name,
                "description": app_info.description,
                "sector": app_info.sector,
                "technologies": app_info.technologies,
                "programming_languages": app_info.programming_languages,
                "security_objectives": app_info.security_objectives
            },
            "threats": {
                "total_count": len(threats),
                "by_severity": self._count_by_severity(threats),
                "threat_ids": [t.id for t in threats]
            },
            "attack_trees": {
                "total_count": len(attack_trees),
                "success_rate": (len(attack_trees) / len(threats)) if threats else 0,
                "total_steps": sum(len(tree.attack_steps) for tree in attack_trees),
                "files_generated": [str(Path(tree.file_path).relative_to(self.output_directory)) for tree in attack_trees]
            },
            "mitre_attack": {
                "techniques_identified": len(all_techniques),
                "technique_frequency": all_techniques,
                "coverage_rate": self._calculate_coverage_rate(attack_trees)
            },
            "processing_stats": processing_stats or {}
        }
        
        with open(summary_file, 'w', encoding='utf-8') as f:
            json.dump(summary_data, f, indent=2, default=str)
        
        self.logger.info(f"JSON summary saved to: {summary_file}")
        return summary_file
    
    def _count_by_severity(self, threats: List[ThreatStatement]) -> Dict[str, int]:
        """Count threats by severity level."""
        counts = {}
        for threat in threats:
            severity = threat.severity or 'unknown'
            counts[severity] = counts.get(severity, 0) + 1
        return counts
    
    def _calculate_coverage_rate(self, attack_trees: List[AttackTree]) -> float:
        """Calculate MITRE ATT&CK coverage rate."""
        if not attack_trees:
            return 0.0
        
        total_steps = sum(len(tree.attack_steps) for tree in attack_trees)
        mapped_steps = sum(
            1 for tree in attack_trees 
            for step in tree.attack_steps 
            if step.mitre_techniques
        )
        
        return (mapped_steps / total_steps) if total_steps > 0 else 0.0