/**
 * Report-stage golden-parity test: given identical state files (scanner context,
 * threats, attack trees, ttp mappings, mitigations), the TS report stage must
 * produce a `threatforest_data.json` bundle structurally identical to Python's.
 *
 * LLM stages are non-deterministic, so the parity contract is enforced on the
 * DETERMINISTIC stages (probability — already covered in probability.test.ts —
 * and report). The fixture state is generated from the real Python report stage
 * (see __fixtures__/report_state/), then both sides run on it and we diff the
 * UI-facing bundle the dashboard depends on.
 *
 * Skipped unless the fixture exists (generated by scripts/gen-report-fixture.py).
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, cpSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';
import { runReportGenerator } from './report.js';

const here = dirname(fileURLToPath(import.meta.url));
const fixtureDir = join(here, '__fixtures__', 'report_state');
const expectedBundle = join(here, '__fixtures__', 'report_expected', 'threatforest_data.json');

const hasFixture = existsSync(fixtureDir) && existsSync(expectedBundle);

test(
  'report stage produces a bundle matching the Python golden output',
  { skip: hasFixture ? false : 'fixture not generated (run scripts/gen-report-fixture.py)' },
  async () => {
    // Stage the fixture state into a temp run dir, run the TS report stage.
    const runDir = mkdtempSync(join(tmpdir(), 'tf-report-parity-'));
    cpSync(fixtureDir, join(runDir, 'state'), { recursive: true });

    await runReportGenerator('/nonexistent-repo', runDir);

    const got = JSON.parse(readFileSync(join(runDir, 'output', 'threatforest_data.json'), 'utf8'));
    const expected = JSON.parse(readFileSync(expectedBundle, 'utf8'));

    // Compare the attack_trees array structurally (the contract the UI graph
    // viewer depends on): per tree, the threat fields, node/edge lists, and the
    // ttc_mappings shape must match.
    assert.equal(
      (got.attack_trees ?? []).length,
      (expected.attack_trees ?? []).length,
      'attack_trees count',
    );
    for (let i = 0; i < expected.attack_trees.length; i++) {
      const g = got.attack_trees[i];
      const e = expected.attack_trees[i];
      assert.equal(g.threat_id, e.threat_id, `tree ${i} threat_id`);
      assert.equal(g.mermaid_code, e.mermaid_code, `tree ${i} mermaid_code`);
      assert.equal(
        JSON.stringify(g.ttc_mappings),
        JSON.stringify(e.ttc_mappings),
        `tree ${i} ttc_mappings`,
      );
    }
  },
);
