'use client';

/**
 * VersionDetailView — TS/Next port of console-ui's VersionDetailPage.jsx.
 *
 * Per-threat dashboard: details bar + interactive attack-tree viewer +
 * mitigations table. Clicking an attack-step badge in the table pans the
 * viewer to the matching node via the focusRequest handshake.
 *
 * react-router (useParams/useNavigate) → next/navigation (useParams/useRouter).
 * CloudscapeShell → AppShell. The AttackFlowViewer pulls in @xyflow/react, which
 * touches the DOM at import time, so it's loaded via next/dynamic with
 * ssr:false to keep it out of the static export's server pass.
 */

import { useState, useEffect, useRef } from 'react';
import { useParams, useRouter } from 'next/navigation';
import dynamic from 'next/dynamic';
import ColumnLayout from '@cloudscape-design/components/column-layout';
import Box from '@cloudscape-design/components/box';
import Header from '@cloudscape-design/components/header';
import Alert from '@cloudscape-design/components/alert';
import Spinner from '@cloudscape-design/components/spinner';
import SpaceBetween from '@cloudscape-design/components/space-between';
import Container from '@cloudscape-design/components/container';
import Badge, { type BadgeProps } from '@cloudscape-design/components/badge';
import Button from '@cloudscape-design/components/button';
import AppShell from '@/components/AppShell';
import MitigationsTable from '@/components/MitigationsTable';
import ExportButton from '@/components/ExportButton';
import { getApplication, getApplicationVersions } from '@/api/client';
import type { ReportAttackTree } from '@/utils/mitigation-aggregator';
import type { FocusRequest } from '@/components/AttackFlowViewer';

// AttackFlowViewer renders @xyflow/react (and reads document/fullscreen), so it
// is browser-only. ssr:false keeps it out of the static-export server pass.
const AttackFlowViewer = dynamic(() => import('@/components/AttackFlowViewer'), {
  ssr: false,
  loading: () => (
    <Box textAlign="center" padding="l" color="text-body-secondary">
      Loading attack tree…
    </Box>
  ),
});

/** Attack-tree bundle carrying the mermaid source the viewer renders. */
type ViewerAttackTree = ReportAttackTree & { mermaid_code?: string; threat_action?: string };

interface VersionData {
  attack_trees?: ViewerAttackTree[];
  extraction_summary?: { total_threats?: number; high_severity_count?: number };
  mapping_summary?: { total_mappings?: number };
  project_info?: { application_name?: string };
  application_name?: string;
  [key: string]: unknown;
}

function PriorityBadge({ priority }: { priority?: string | null }) {
  const colorMap: Record<string, BadgeProps['color']> = { High: 'red', Medium: 'grey', Low: 'green' };
  return <Badge color={(priority && colorMap[priority]) || 'grey'}>{priority || '—'}</Badge>;
}

function ThreatDetailsBar({ tree }: { tree: ViewerAttackTree | null }) {
  if (!tree) return null;
  return (
    <Container>
      <ColumnLayout columns={2} variant="text-grid">
        <div>
          <Box variant="awsui-key-label">Threat Statement</Box>
          <div>{tree.threat_statement || '—'}</div>
        </div>
        <div>
          <SpaceBetween size="m">
            <div>
              <Box variant="awsui-key-label">Priority</Box>
              <PriorityBadge priority={tree.priority as string} />
            </div>
            <div>
              <Box variant="awsui-key-label">Action</Box>
              <div>{tree.threat_action || '—'}</div>
            </div>
            <div>
              <Box variant="awsui-key-label">Source</Box>
              <div>
                {tree.threatSource === 'generated'
                  ? 'Generated by ThreatForest'
                  : (tree.threatSource as string) || '—'}
              </div>
            </div>
          </SpaceBetween>
        </div>
      </ColumnLayout>
    </Container>
  );
}

export default function VersionDetailView() {
  const { appId, versionId, threatIndex } = useParams<{
    appId: string;
    versionId: string;
    threatIndex: string;
  }>();
  const router = useRouter();
  const selectedIdx = parseInt(threatIndex || '0', 10);
  const [data, setData] = useState<VersionData | null>(null);
  const [appName, setAppName] = useState<string>(appId);
  // True once a persistent app record is found — blocks the legacy
  // project_info.application_name fallback from clobbering the real name.
  const [persistentAppLoaded, setPersistentAppLoaded] = useState(false);
  const [versionLabel, setVersionLabel] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  // Bumped each time the user clicks an attack-step badge in the mitigations
  // table so the AttackFlowViewer pans/highlights the matching node. Pairs the
  // step id with a counter so clicking the *same* step twice still re-fires
  // the focus effect (otherwise React would skip the second re-render).
  const [focusRequest, setFocusRequest] = useState<FocusRequest & { ts: number }>({
    stepId: undefined,
    ts: 0,
  });
  // Anchor for scrolling the attack-tree viewer into view when the user
  // clicks a step badge while scrolled below it.
  const attackTreeAnchorRef = useRef<HTMLDivElement>(null);

  function handleFocusStep(stepId: string) {
    if (attackTreeAnchorRef.current) {
      attackTreeAnchorRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
    setFocusRequest({ stepId, ts: Date.now() });
  }

  useEffect(() => {
    let cancelled = false;
    async function fetchVersion() {
      try {
        setLoading(true);
        setError(null);
        const response = await fetch(
          `/api/applications/${encodeURIComponent(appId)}/versions/${encodeURIComponent(versionId)}/data`,
        );
        if (!response.ok) throw new Error(`Failed to load (HTTP ${response.status})`);
        const json = (await response.json()) as VersionData;
        if (cancelled) return;
        setData(json);
        if (!persistentAppLoaded) {
          if (json.project_info?.application_name) setAppName(json.project_info.application_name);
          else if (json.application_name) setAppName(json.application_name);
        }
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : 'Failed to load');
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    fetchVersion();
    return () => {
      cancelled = true;
    };
  }, [appId, versionId, persistentAppLoaded]);

  // Authoritative app name from the persistent record (works for both
  // opaque app_id and folder-slug URLs thanks to the /by-id fallback).
  useEffect(() => {
    let cancelled = false;
    getApplication(appId)
      .then((app) => {
        if (cancelled || !app?.name) return;
        setAppName(app.name);
        setPersistentAppLoaded(true);
      })
      .catch(() => {
        /* keep legacy fallback */
      });
    return () => {
      cancelled = true;
    };
  }, [appId]);

  // Friendly version label for the breadcrumb.
  useEffect(() => {
    let cancelled = false;
    if (versionId === 'latest') {
      setVersionLabel('Latest');
      return () => {
        cancelled = true;
      };
    }
    getApplicationVersions(appId)
      .then(({ versions = [] }) => {
        if (cancelled) return;
        const match = versions.find((v) => v.id === versionId);
        setVersionLabel(match?.display_name || versionId);
      })
      .catch(() => {
        if (!cancelled) setVersionLabel(versionId);
      });
    return () => {
      cancelled = true;
    };
  }, [appId, versionId]);

  const attackTrees = data?.attack_trees || [];
  const selectedTree = attackTrees[selectedIdx] || null;
  const threatLabel = selectedTree
    ? `${selectedTree.threat_id || `Threat ${selectedIdx + 1}`} — ${selectedTree.threat_category || 'Unknown'}`
    : `Threat ${selectedIdx + 1}`;

  return (
    <AppShell
      activePage="/applications"
      breadcrumbs={[
        { text: 'Home', href: '/' },
        { text: 'Applications', href: '/applications' },
        { text: appName, href: `/applications/${appId}` },
        {
          text: versionLabel || 'Latest threat model',
          href: `/applications/${appId}/versions/${versionId}`,
        },
        {
          text: threatLabel,
          href: `/applications/${appId}/versions/${versionId}/threats/${threatIndex}`,
        },
      ]}
    >
      {error && <Alert type="error" header="Error loading dashboard">{error}</Alert>}
      {loading ? (
        <Box textAlign="center" padding="l" data-testid="loading-spinner">
          <Spinner size="large" />
        </Box>
      ) : data ? (
        <SpaceBetween size="m">
          <Header
            variant="h1"
            actions={
              <SpaceBetween direction="horizontal" size="xs">
                <Button
                  iconName="angle-left"
                  variant="icon"
                  disabled={selectedIdx <= 0}
                  onClick={() =>
                    router.push(`/applications/${appId}/versions/${versionId}/threats/${selectedIdx - 1}`)
                  }
                  ariaLabel="Previous threat"
                />
                <Box variant="p" display="inline" padding={{ top: 'xxs' }}>
                  {selectedIdx + 1} / {attackTrees.length}
                </Box>
                <Button
                  iconName="angle-right"
                  variant="icon"
                  disabled={selectedIdx >= attackTrees.length - 1}
                  onClick={() =>
                    router.push(`/applications/${appId}/versions/${versionId}/threats/${selectedIdx + 1}`)
                  }
                  ariaLabel="Next threat"
                />
                <ExportButton
                  summaryData={data}
                  appId={appId}
                  versionId={versionId}
                  appName={appName}
                  versionLabel={versionLabel}
                />
              </SpaceBetween>
            }
          >
            {threatLabel}
          </Header>
          {selectedTree && <ThreatDetailsBar tree={selectedTree} />}
          {selectedTree && (
            <div ref={attackTreeAnchorRef}>
              <Header variant="h3">Attack Tree</Header>
              <Box variant="p" color="text-status-inactive" fontSize="body-s" margin={{ bottom: 'xs' }}>
                Click any node to view and edit its properties in the right panel.
              </Box>
              <div style={{ border: '1px solid #d5dbdb', borderRadius: 8, overflow: 'hidden' }}>
                <AttackFlowViewer attackTree={selectedTree} focusRequest={focusRequest} />
              </div>
            </div>
          )}
          {selectedTree && (
            <MitigationsTable
              attackTree={selectedTree}
              onFocusStep={handleFocusStep}
              appId={appId}
              versionId={versionId}
            />
          )}
          {!selectedTree && (
            <Box color="text-status-inactive" textAlign="center" padding="l">
              Attack tree not found for this threat.
            </Box>
          )}
        </SpaceBetween>
      ) : null}
    </AppShell>
  );
}
