"""Property-based tests for the Stencil CDN injector.

Uses Hypothesis to verify that inject_stencil_references correctly injects
Stencil CDN resources and ThreatForest CSS custom properties into any valid
HTML file containing a </head> tag.
"""

from __future__ import annotations

import shutil
import string
import tempfile
from pathlib import Path

from hypothesis import given, settings, HealthCheck
from hypothesis import strategies as st

from server.stencil_injector import (
    STENCIL_CSS_URL,
    STENCIL_ESM_JS_URL,
    STENCIL_JS_URL,
    THREATFOREST_CSS_PROPERTIES,
    inject_stencil_references,
)

# ---------------------------------------------------------------------------
# Hypothesis settings — minimum 100 examples per property
# ---------------------------------------------------------------------------

PBT_SETTINGS = settings(
    max_examples=100,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
    deadline=None,
)

# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

# Safe characters for generating random HTML-like content
_SAFE_TEXT = string.ascii_letters + string.digits + " \t\n"

# Random text that could appear in an HTML body (no angle brackets to keep
# the HTML structure predictable)
safe_text = st.text(alphabet=_SAFE_TEXT, min_size=0, max_size=200)

# Random tag names for extra head content
_TAG_NAMES = ["meta", "link", "title", "style", "script"]
head_tag_name = st.sampled_from(_TAG_NAMES)

# Variation of </head> casing — the injector does case-insensitive matching
head_close_variants = st.sampled_from([
    "</head>", "</Head>", "</HEAD>", "</hEaD>",
])


@st.composite
def random_html_with_head(draw: st.DrawFn) -> str:
    """Generate a random but structurally valid HTML string with a </head> tag.

    The generated HTML has:
    - Optional doctype
    - <html> wrapper
    - <head> with random inner content and a closing </head> (random casing)
    - <body> with random content
    """
    has_doctype = draw(st.booleans())
    head_content = draw(safe_text)
    body_content = draw(safe_text)
    head_close = draw(head_close_variants)

    # Optionally add extra tags inside <head>
    num_extra_tags = draw(st.integers(min_value=0, max_value=3))
    extra_head = ""
    for _ in range(num_extra_tags):
        tag = draw(head_tag_name)
        attr_val = draw(st.text(alphabet=string.ascii_lowercase, min_size=0, max_size=10))
        extra_head += f'<{tag} data-test="{attr_val}"></{tag}>\n'

    doctype = "<!DOCTYPE html>\n" if has_doctype else ""
    return (
        f"{doctype}<html>\n"
        f"<head>\n{extra_head}{head_content}\n{head_close}\n"
        f"<body>\n{body_content}\n</body>\n</html>"
    )


def _write_html(content: str) -> Path:
    """Write HTML content to a temp file and return its path."""
    tmp_dir = Path(tempfile.mkdtemp())
    p = tmp_dir / "attack_trees_dashboard.html"
    p.write_text(content, encoding="utf-8")
    return p


# ---------------------------------------------------------------------------
# Property 12: Stencil CDN inclusion in generated HTML
# ---------------------------------------------------------------------------
# Feature: threatforest-landing-page, Property 12: Stencil CDN inclusion in generated HTML
# For any Dashboard_Output HTML file generated by the pipeline, the HTML SHALL
# contain the Stencil CDN stylesheet link and script tags, and SHALL reference
# the ThreatForest CSS custom properties.
# Validates: Requirements 9.2, 9.4


class TestProperty12StencilCDNInclusion:
    """Property 12: Stencil CDN inclusion in generated HTML."""

    @given(html=random_html_with_head())
    @PBT_SETTINGS
    def test_stencil_css_link_present_after_injection(self, html: str) -> None:
        """After injection, the HTML contains the Stencil CDN stylesheet link."""
        path = _write_html(html)
        try:
            result = inject_stencil_references(path)
            assert result is True
            modified = path.read_text(encoding="utf-8")
            assert STENCIL_CSS_URL in modified
        finally:
            shutil.rmtree(path.parent, ignore_errors=True)

    @given(html=random_html_with_head())
    @PBT_SETTINGS
    def test_stencil_esm_js_present_after_injection(self, html: str) -> None:
        """After injection, the HTML contains the Stencil ESM JS script tag."""
        path = _write_html(html)
        try:
            result = inject_stencil_references(path)
            assert result is True
            modified = path.read_text(encoding="utf-8")
            assert STENCIL_ESM_JS_URL in modified
            assert 'type="module"' in modified
        finally:
            shutil.rmtree(path.parent, ignore_errors=True)

    @given(html=random_html_with_head())
    @PBT_SETTINGS
    def test_stencil_nomodule_js_present_after_injection(self, html: str) -> None:
        """After injection, the HTML contains the Stencil nomodule JS script tag."""
        path = _write_html(html)
        try:
            result = inject_stencil_references(path)
            assert result is True
            modified = path.read_text(encoding="utf-8")
            assert STENCIL_JS_URL in modified
            assert "nomodule" in modified
        finally:
            shutil.rmtree(path.parent, ignore_errors=True)

    @given(html=random_html_with_head())
    @PBT_SETTINGS
    def test_threatforest_css_custom_properties_present(self, html: str) -> None:
        """After injection, the HTML references all ThreatForest CSS custom properties."""
        path = _write_html(html)
        try:
            result = inject_stencil_references(path)
            assert result is True
            modified = path.read_text(encoding="utf-8")

            required_props = [
                "--tf-primary:",
                "--tf-primary-dark:",
                "--tf-accent:",
                "--tf-bg:",
                "--tf-surface:",
                "--tf-text:",
                "--tf-border:",
            ]
            for prop in required_props:
                assert prop in modified, f"Missing CSS custom property: {prop}"
        finally:
            shutil.rmtree(path.parent, ignore_errors=True)

    @given(html=random_html_with_head())
    @PBT_SETTINGS
    def test_injected_content_appears_before_head_close(self, html: str) -> None:
        """The injected Stencil references appear before the </head> tag."""
        path = _write_html(html)
        try:
            inject_stencil_references(path)
            modified = path.read_text(encoding="utf-8")

            css_pos = modified.find(STENCIL_CSS_URL)
            head_close_pos = modified.lower().find("</head>")

            assert css_pos != -1, "Stencil CSS URL not found"
            assert head_close_pos != -1, "</head> tag not found"
            assert css_pos < head_close_pos, (
                "Stencil CSS link should appear before </head>"
            )
        finally:
            shutil.rmtree(path.parent, ignore_errors=True)

    @given(html=random_html_with_head())
    @PBT_SETTINGS
    def test_original_content_preserved(self, html: str) -> None:
        """Injection preserves all original HTML content."""
        path = _write_html(html)
        try:
            inject_stencil_references(path)
            modified = path.read_text(encoding="utf-8")

            # The original body content should still be present.
            # Extract body content from original HTML.
            body_start = html.lower().find("<body")
            if body_start != -1:
                body_end = html.lower().find("</body>")
                if body_end != -1:
                    original_body = html[body_start:body_end + len("</body>")]
                    assert original_body in modified, (
                        "Original body content was altered by injection"
                    )
        finally:
            shutil.rmtree(path.parent, ignore_errors=True)

    @given(html=random_html_with_head())
    @PBT_SETTINGS
    def test_idempotent_injection(self, html: str) -> None:
        """Calling inject_stencil_references twice produces the same result."""
        path = _write_html(html)
        try:
            inject_stencil_references(path)
            first = path.read_text(encoding="utf-8")

            inject_stencil_references(path)
            second = path.read_text(encoding="utf-8")

            assert first == second, "Injection is not idempotent"
            assert second.count(STENCIL_CSS_URL) == 1, (
                "Stencil CSS URL duplicated on second injection"
            )
        finally:
            shutil.rmtree(path.parent, ignore_errors=True)
