"""File generation for summary reports"""
import json
from typing import Dict, Any, List
from pathlib import Path
from datetime import datetime
from .report_formatters import ReportFormatters


class PathEncoder(json.JSONEncoder):
    """Custom JSON encoder to handle Path objects"""
    def default(self, obj):
        if isinstance(obj, Path):
            return str(obj)
        return super().default(obj)


class FileGenerators:
    """Generates report files"""
    
    def __init__(self, logger, formatters: ReportFormatters):
        self.logger = logger
        self.fmt = formatters
    
    def generate_main_summary(self, output_path: Path, attack_trees: Dict, extracted_info: Dict) -> str:
        """Generate main summary report"""
        project_info = extracted_info.get('project_info', {})
        extraction_summary = extracted_info.get('extraction_summary', {})
        
        trees = attack_trees.get('ttc_mapped_trees', []) or attack_trees.get('attack_trees', [])
        successful = [t for t in trees if 'mermaid_code' in t]
        failed = [t for t in trees if 'error' in t]
        
        content = f"""# ThreatForest Analysis Report

**Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Executive Summary

This report presents a comprehensive threat analysis for **{project_info.get('application_name', 'Unknown Application')}**.

## Project Information

- **Application Name**: {project_info.get('application_name', 'Unknown')}
- **Architecture Type**: {project_info.get('architecture_type', 'Unknown')}
- **Deployment Environment**: {project_info.get('deployment_environment', 'Unknown')}
- **Industry Sector**: {project_info.get('sector', 'Unknown')}

### Technology Stack
{self.fmt.format_technologies(project_info.get('technologies', []))}

### Security Objectives
{self.fmt.format_security_objectives(project_info.get('security_objectives', {}))}

## Threat Analysis Results

- **Total Threats**: {extraction_summary.get('total_threats', 0)}
- **High Severity**: {extraction_summary.get('high_severity_count', 0)}
- **Attack Trees Generated**: {len(successful)}

### High Severity Threats
{self.fmt.format_high_severity_threats(extracted_info.get('high_severity_threats', []))}

## Attack Tree Analysis

### Generated Attack Trees
{self.fmt.format_attack_trees_summary(successful)}

{self.fmt.format_failed_trees(failed)}

## Recommendations

1. **Address High Severity Threats**: Focus on the {extraction_summary.get('high_severity_count', 0)} high severity threats
2. **Implement Security Controls**: Deploy mitigations from attack trees
3. **Review Attack Paths**: Analyze generated attack trees

---
*Generated by ThreatForest*
"""
        
        summary_file = output_path / "threatforest_analysis_report.md"
        summary_file.write_text(content)
        return str(summary_file)
    
    def generate_attack_tree_files(self, output_path: Path, trees: List[Dict]) -> List[str]:
        """Generate individual attack tree markdown files"""
        tree_files = []
        
        for tree in trees:
            if not isinstance(tree, dict) or 'mermaid_code' not in tree:
                continue
            
            threat_id = tree.get('threat_id', 'unknown')
            threat_statement = tree.get('threat_statement', tree.get('statement', ''))
            category = tree.get('threat_category', tree.get('category', 'Unknown'))
            
            filename = f"attack_tree_{threat_id}_{category.lower().replace(' ', '_')}.md"
            file_path = output_path / filename
            
            content = f"""# Attack Tree: {category}

**Threat ID**: {threat_id}
**Statement**: {threat_statement}

## Attack Tree Diagram

```mermaid
{tree.get('mermaid_code', '')}
```

## Attack Path Analysis

Review this attack tree to:
1. Identify critical attack paths
2. Implement appropriate security controls
3. Monitor for indicators
4. Develop incident response procedures

---
*Generated by ThreatForest*
"""
            
            try:
                file_path.write_text(content, encoding='utf-8')
                tree_files.append(str(file_path))
                print(f"💾 Generated: {filename}")
            except Exception as e:
                self.logger.warning(f"Failed to write {filename}: {e}")
        
        return tree_files
    
    def generate_json_export(self, output_path: Path, attack_trees: Dict, extracted_info: Dict) -> str:
        """Generate JSON data export"""
        trees = attack_trees.get('ttc_mapped_trees', []) or attack_trees.get('attack_trees', [])
        
        export_data = {
            "metadata": {
                "generated_at": datetime.now().isoformat(),
                "generator": "ThreatForest",
                "version": "1.0"
            },
            "project_info": extracted_info.get('project_info', {}),
            "extraction_summary": extracted_info.get('extraction_summary', {}),
            "threats": {
                "all_threats": extracted_info.get('threat_statements', []),
                "high_severity": extracted_info.get('high_severity_threats', [])
            },
            "attack_trees": trees,
            "mapping_summary": attack_trees.get('mapping_summary', {})
        }
        
        json_file = output_path / "threatforest_data.json"
        with open(json_file, 'w') as f:
            json.dump(export_data, f, indent=2, cls=PathEncoder)
        
        return str(json_file)
